LTO_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

VIA_ENABLE = yes
VIAL_ENABLE = yes

ENCODER_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIALRGB_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = yes
SWAP_HANDS_ENABLE = no

QMK_SETTINGS = no
MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no

BOOTMAGIC_ENABLE = no
MAGIC_ENABLE = no

